### ISSUE TITLE
Running test action each for n replicas

### ISSUE THREAD

**Issue by wgrzelak** [GoogleCloudPlatform/marketplace-testrunner#13]
For example, Google Click to Deploy Cassandra K8s app can have multiple replicas, it means that we should tests all of them.

Now, it uses `bashTest` and `for` loop provided by `Bash`, see https://github.com/GoogleCloudPlatform/click-to-deploy/blob/55157436d62d133c98a98bccd5001bf83d1c34a4/k8s/cassandra/apptest/tester/tests/basic-suite.yaml#L13-L28.

It has an issue that one action runs multiple tests. If this action fails, it doesn't mean that all Pods are not working.

I think we can use Go template to improve this. Having a loop in a Go template level can help split such tests to each action.

For example:

```yaml
{{ for pod in .REPLICAS }}
- name: Execute CQL query on {{ pod }} Pod
  bashTest:
    script: |-
      set -e
      DOMAIN="${APP_INSTANCE_NAME}-cassandra-svc.${NAMESPACE}.svc.cluster.local"
      export CQLSH_HOST="${APP_INSTANCE_NAME}-cassandra-{{ pod }}.${DOMAIN}"
      cqlsh -e "SHOW HOST" --cqlversion="3.4.4"
    expect:
      exitCode:
        equals: 0
{{ endfor }}
```
